import { dir } from "i18next";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApiCalls } from "./ApiCalls";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { CssBaseline, Box } from "@mui/material";
import { theme } from './muiTheme';
import { Suspense } from "react";
import { AppLayout } from "./AppLayout";
const inter = Inter({ subsets: ["latin"] });

const languages=["en","fr","kr"]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default function RootLayout({
  children,
  params: { lng }
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string };
}>) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Box sx={{ height: "100vh", overflow: "auto" }}>
              <CssBaseline />
              <Suspense>
                <ApiCalls/>
              </Suspense>
              <AppLayout lng={lng}>
                {children}
              </AppLayout>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
